name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          mkdir package
          pip install -r requirements.txt --target ./package

      - name: Zip Lambda function
        run: |
          cd package
          zip -r ../my_deployment_package.zip .
          cd ..
          zip my_deployment_package.zip lambda_function.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name portfolio-postgres-api --zip-file fileb://my_deployment_package.zip
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: example-artifact
          path: my_deployment_package.zip